import type { ProjectRecord } from "@/server/domain/project";

export const demoProjectFixture: ProjectRecord = {
  id: "clonable-v1",
  slug: "clonable-v1",
  name: "Clonable V1 Foundation",
  summary:
    "A planning-first local AI builder focused on defining the MVP, showing progress clearly, and executing inside a real Git workspace.",
  status: "Building",
  currentFocus:
    "Ship the policy-driven dashboard and task flow before expanding into autonomous execution.",
  vision:
    "Build a serious local-first hybrid AI product that turns ideas into working MVPs and keeps building momentum visible after the first generation pass.",
  plannerState: "succeeded",
  plannerMessage: "Planner draft ready for review.",
  targetUser: "Solo founders and indie builders",
  ideaPrompt:
    "Create a local-first hybrid AI builder that helps a user define an MVP, plan the work, and continue shipping inside a real Git workspace.",
  stackPreferences: ["Next.js", "TypeScript", "Tailwind", "SQLite"],
  defaultChatBotId: "mvp-guide",
  constraints: [
    "Prefer boring, stable technologies",
    "Keep local-first and self-hostable",
    "Avoid token-gating product behavior",
    "Optimize for ADHD-friendly clarity",
  ],
  definitionOfDone: [
    "The MVP boundary is explicit.",
    "Task ownership is visible and policy-safe.",
    "Workspace and preview stay inspectable and recoverable.",
  ],
  mvp: {
    goalStatement:
      "Help a user turn an idea into a working MVP through structured planning, task orchestration, and local repo-based execution.",
    summary:
      "A user can create a project from a prompt, define a realistic MVP, review phases, features, and tasks, configure agents, track progress, and work in a local Git-backed workspace.",
    successDefinition:
      "The MVP is successful when the user always knows the goal, current MVP boundary, current phase, next best tasks, active agents, recent progress, and blockers.",
    laterScope: [
      "Advanced deployment matrix",
      "Deep concurrent multi-agent editing",
      "Multi-user collaboration",
      "Visual page editor",
    ],
    boundaryReasoning:
      "V1 keeps a tight loop around planning, visible progress, serialized workspace writes, and understandable failures so the product is reusable rather than flashy.",
    constraints: [
      "Prefer boring, stable technologies",
      "Keep local-first and self-hostable",
      "Avoid token-gating product behavior",
      "Optimize for ADHD-friendly clarity",
    ],
  },
  phases: [
    {
      id: "phase-foundation",
      title: "Foundation",
      goal: "Define the product contract and deliver a stable shell.",
      status: "In Progress",
      sortOrder: 1,
    },
    {
      id: "phase-planning-core",
      title: "Planning Core",
      goal: "Capture idea, define MVP, and manage structured planning.",
      status: "Planned",
      sortOrder: 2,
    },
  ],
  features: [
    {
      id: "feature-mvp-contract",
      phaseId: "phase-foundation",
      title: "Product contract and MVP boundary",
      summary: "Turn the big idea into a credible V1 contract and scope edge.",
      status: "Done",
      priority: "high",
      sortOrder: 1,
    },
    {
      id: "feature-dashboard-shell",
      phaseId: "phase-foundation",
      title: "ADHD-friendly dashboard shell",
      summary: "Show goal, MVP, phase focus, momentum, and blockers at a glance.",
      status: "In Progress",
      priority: "high",
      sortOrder: 2,
    },
  ],
  tasks: [
    {
      id: "task-prd",
      phaseId: "phase-foundation",
      featureId: "feature-mvp-contract",
      title: "Write concise product definition and V1 PRD",
      description:
        "Capture the product promise, V1 scope, goals, non-goals, and success criteria.",
      state: "Done",
      ownerAgentId: "agent-reviewer",
      priority: "high",
      acceptanceCriteria: [
        "Product definition is concise and clear",
        "V1 scope is separated from non-goals",
      ],
      lastUpdated: "2026-03-13T22:10:00.000Z",
      notes: "Core product contract documented.",
      collectiveQa: undefined,
      nextRole: undefined,
      parentTaskId: undefined,
      subTaskIds: [],
      dependencies: [],
      optionalDependencies: [],
      blockerReason: undefined,
      waitingReason: undefined,
      lastImplementationOwnerAgentId: "agent-docs",
      requiresUser: false,
      reviewDate: undefined,
      changeLog: [
        {
          timestamp: "2026-03-13T22:10:00.000Z",
          agentId: "agent-reviewer",
          field: "state",
          from: "QA_Review",
          to: "Done",
        },
      ],
      rejectionLog: [],
      relatedFiles: ["docs/foundation/01-product-definition.md"],
      artifacts: ["foundation docs"],
      completedAt: "2026-03-13T22:10:00.000Z",
    },
    {
      id: "task-persistence",
      phaseId: "phase-planning-core",
      featureId: "feature-dashboard-shell",
      title: "Replace demo data with SQLite persistence",
      description: "Move the app from hard-coded state to a real local database.",
      state: "Ready",
      ownerAgentId: "agent-backend",
      priority: "high",
      acceptanceCriteria: ["Projects persist across restarts"],
      lastUpdated: "2026-03-14T00:00:00.000Z",
      notes: "Foundation branch is in place.",
      collectiveQa: undefined,
      nextRole: "builder",
      parentTaskId: undefined,
      subTaskIds: [],
      dependencies: [],
      optionalDependencies: [],
      blockerReason: undefined,
      waitingReason: undefined,
      lastImplementationOwnerAgentId: undefined,
      requiresUser: false,
      reviewDate: undefined,
      changeLog: [
        {
          timestamp: "2026-03-14T00:00:00.000Z",
          agentId: "agent-manager",
          field: "state",
          from: "Backlog",
          to: "Ready",
        },
      ],
      rejectionLog: [],
      relatedFiles: ["src/server/infrastructure"],
      artifacts: ["repository layer"],
      completedAt: undefined,
    },
  ],
  agents: [
    {
      id: "agent-manager",
      name: "Project Manager",
      role: "Keep flow visible, safe, and unblocked.",
      policyRole: "orchestrator",
      runtimeBackend: "openclaw",
      provider: undefined,
      model: "OpenClaw",
      fallbackProviders: [],
      openclawBotId: "delivery-orchestrator",
      status: "active",
      enabled: true,
      instructionsSummary: "Own routing, ownership, stale handling, and task transitions.",
      instructions:
        "You are the Orchestrator. Assign owners before Ready, enforce policy transitions, and keep deadlocks visible.",
      permissions: ["move tasks", "reassign tasks", "split tasks", "override task state"],
      boundaries: ["must log automatic decisions"],
      escalationRules: ["escalate only when requires_user is true"],
      wipLimit: 0,
      canWriteWorkspace: false,
      currentTaskId: "task-persistence",
    },
    {
      id: "agent-backend",
      name: "Backend Builder",
      role: "Implement persistence, orchestration, and local integrations.",
      policyRole: "builder",
      runtimeBackend: "provider",
      provider: "openai",
      model: "GPT-5.3-Codex",
      fallbackProviders: [],
      status: "ready",
      enabled: true,
      instructionsSummary: "Own repository abstractions, orchestration services, and runtime control.",
      instructions:
        "You are the Backend Builder. Implement assigned backend tasks safely and attach clear artifacts.",
      permissions: ["edit server files", "define repositories", "attach logs"],
      boundaries: ["one write task at a time"],
      escalationRules: ["escalate risky infra additions"],
      wipLimit: 1,
      canWriteWorkspace: true,
      currentTaskId: "task-persistence",
    },
    {
      id: "agent-reviewer",
      name: "Reviewer",
      role: "Validate output against acceptance criteria.",
      policyRole: "tester",
      runtimeBackend: "openclaw",
      provider: undefined,
      model: "OpenClaw",
      fallbackProviders: [],
      openclawBotId: "quality-guardian",
      status: "active",
      enabled: true,
      instructionsSummary: "Review for regressions, scope drift, and missing acceptance evidence before Done.",
      instructions:
        "You are the Tester. Validate assigned QA tasks against acceptance criteria, task evidence, and artifacts.",
      permissions: ["review tasks", "request rework", "log findings"],
      boundaries: ["does not directly edit code in normal flow"],
      escalationRules: ["escalate ambiguous acceptance criteria"],
      wipLimit: 3,
      canWriteWorkspace: false,
      currentTaskId: undefined,
    },
  ],
  events: [
    {
      id: "event-foundation",
      createdAt: "2026-03-13T22:11:00.000Z",
      type: "system",
      summary: "Foundation scaffold created",
      reason: "Clonable has a working shell and documented V1 contract.",
    },
  ],
  agentRuns: [],
  runtime: {
    orchestrationEnabled: false,
    runnerStatus: "idle",
  },
  workspace: {
    rootPath: "C:\\Users\\jimmi\\Documents\\GitHub\\Clonable.dev",
    repoProvider: "Local Git",
    branch: "main",
    lastCommit: "Bootstrap Clonable foundation",
    dirtyFiles: [],
    files: [],
  },
  preview: {
    status: "Stopped",
    command: "npm run dev",
    port: 3000,
    url: "http://localhost:3000",
    recentLogs: [
      {
        at: "2026-03-13T22:12:00.000Z",
        line: "Preview not started yet.",
      },
    ],
  },
};
